using System.Text.Json.Serialization;

namespace FyreWorksAI.Shared.Core.Models.Jobs;

//******************************//
//******* Job Financials *******//
//******************************//

public sealed class ChangeOrderRecord
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public DateTime ApprovedOn { get; set; } = DateTime.Today;
    public string Title { get; set; } = string.Empty;
    public decimal RevenueAmount { get; set; }
    public decimal EstimatedCostImpact { get; set; }
    public bool Approved { get; set; } = true;
    public string Notes { get; set; } = string.Empty;
    public List<AttachmentRecord> Attachments { get; set; } = [];
}

public sealed class ScheduleValueItem
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Description { get; set; } = string.Empty;
    public string CategoryCode { get; set; } = JobCostCodes.Other;
    public decimal ReferenceValue { get; set; }
    public decimal ScheduledValue { get; set; }
    public decimal PercentageOfTotal { get; set; }
    public decimal BilledToDate { get; set; }
    public decimal PaidToDate { get; set; }
    public Guid? LinkedChangeOrderId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public bool IsPercentageManual { get; set; }
    public string Notes { get; set; } = string.Empty;
    public List<ScheduleValueSubLine> SubLines { get; set; } = [];

    [JsonIgnore]
    public bool IsChangeOrderLine => LinkedChangeOrderId is not null;

    [JsonIgnore]
    public decimal RemainingToBill => Math.Max(0m, ScheduledValue - BilledToDate);
}

public sealed class ScheduleValueSubLine
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string Description { get; set; } = string.Empty;
    public decimal LineValue { get; set; }
    public decimal BilledAmount { get; set; }
    public decimal PaidAmount { get; set; }
    public Guid? LinkedCommitmentId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string Notes { get; set; } = string.Empty;
}

public sealed class CommitmentRecord
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string CommitmentNumber { get; set; } = string.Empty;
    public string Vendor { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public Guid? ScheduleValueItemId { get; set; }
    public decimal CommittedAmount { get; set; }
    public decimal BilledAmount { get; set; }
    public decimal PaidAmount { get; set; }
    public string InvoiceNumber { get; set; } = string.Empty;
    public DateTime InvoiceDate { get; set; } = DateTime.Today;
    public DateTime DueDate { get; set; } = DateTime.Today.AddDays(30);
    public string Notes { get; set; } = string.Empty;
}
